Select * from students;
select * from department;
SELECT * FROM COURSE;

SELECT S.PHONE_nUMBER, D.DEPARTMENT_NAME
FROM STUDENTS S
JOIN DEPARTMENT D
ON S.DEPARTMENT_ID = D.DEPARTMENT_ID;

SELECT S.STUDENT_NAME, C.COURSE_NAME
FROM COURSE C
JOIN STUDENTS S
ON C.DEPT_ID = S.DEPARTMENT_ID;

SELECT S.PHONE_NUMBER, C.COURSE_NAME
FROM COURSE C
INNER JOIN STUDENTS S
ON C.DEPT_ID = S.DEPARTMENT_ID;


