--DROP TABLE USERS;
--DROP TABLE COUNTRIES;
--DROP TABLE WATCH_HISTORY;

SELECT * FROM USERS;
SELECT * FROM  COUNTRIES;
SELECT * FROM WATCH_HISTORY;

SELECT U.USER_NAME, C.COUNTRY_NAME
FROM USERS U
INNER JOIN COUNTRIES C
ON C.COUNTRY_ID = U.COUNTRY_ID;

SELECT U.USER_NAME, w.movie_name
FROM USERS U
INNER JOIN WATCH_HISTORY W
ON U.COUNTRY_ID = W.COUNTRY_ID;

SELECT U.USER_NAME, w.movie_name
FROM USERS U
LEFT JOIN WATCH_HISTORY W
ON U.COUNTRY_ID = W.COUNTRY_ID;

SELECT U.USER_NAME, w.movie_name
FROM WATCH_HISTORY W
RIGHT JOIN USERS U
ON U.USER_ID = W.USER_ID;

SELECT U.USER_NAME, W.MOVIE_NAME
FROM USERS U
FULL OUTER JOIN WATCH_HISTORY W
ON U.COUNTRY_ID = W.COUNTRY_ID;

SELECT U.USER_NAME, C.COUNTRY_NAME
FROM USERS U
CROSS JOIN COUNTRIES C;

SELECT A.USER_NAME, B.USER_NAME
FROM USERS A
JOIN USERS B
ON A.COUNTRY_ID = B.COUNTRY_ID;
