SELECT * FROM DEPARTMENT;
SELECT * FROM COURSE;
SELECT * FROM STUDENTS;

--🟠 LEVEL 8 — ALTER TABLE
--
--Q29. Add a new column EMAIL to the DEPARTMENT table with datatype VARCHAR2(100).
ALTER TABLE DEPARTMENT
ADD EMAIL VARCHAR2(100);
--Q30. Add a new column ROOM_NUMBER to the COURSE table with datatype NUMBER.
ALTER TABLE COURSE
ADD ROOM_NUMBER NUMBER;
--Q31. Add a new column ADDRESS to the STUDENTS table with datatype VARCHAR2(200).
ALTER TABLE STUDENTS
ADD ADDRESS VARCHAR2(200);

--Q32. Remove the ROOM_NUMBER column from the COURSE table.
ALTER TABLE COURSE
DROP COLUMN ROOM_NUMBER;
--Q33. Remove the ADDRESS column from the STUDENTS table.
ALTER TABLE STUDENTS
DROP COLUMN ADDRESS;