CREATE TABLE Friends (
    ID NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    Name VARCHAR2(100) NOT NULL,
    Gender VARCHAR2(10),
    Email VARCHAR2(100) UNIQUE,
    DOB DATE
);

SELECT * FROM FRIENDS;

INSERT INTO FRIENDS(Name,Gender,Email,DOB)
VALUES('Maryam','Female','maryam@gmail.com', DATE '2005-08-21');

INSERT INTO FRIENDS(Name,Gender,Email,DOB)
VALUES('Ayesha','Female','ayesha@gmail.com',DATE '2003-09-12');

INSERT INTO FRIENDS(Name,Gender,Email,DOB)
VALUES('Areeba','Female','areeba@gmail.com',DATE '2006-03-12');

INSERT INTO FRIENDS(Name,Gender,Email,DOB)
VALUES('Bilal','Male','bilal@gmail.com',DATE '2003-12-12');

INSERT INTO FRIENDS(Name,Gender,Email,DOB)
VALUES('Muhammad','Male','muhammad@gmail.com',DATE '2009-6-16');

INSERT INTO FRIENDS(Name,Gender,Email,DOB)
VALUES('Maya','Female','maya@gmail.com',DATE '2003-09-12');


INSERT INTO FRIENDS(Name,Gender,Email,DOB)
VALUES('Saim','Male','saim@gmail.com',DATE '2017-7-12');

COMMIT;

--Adding age Column
ALTER TABLE Friends
ADD AGE NUMBER

UPDATE FRIENDS
SET AGE = FLOOR(MONTHS_BETWEEN(SYSDATE,DOB)/12);
COMMIT;

--Floor Rounds the age down to the nearest whole number (removes decimals).
--SYSDATE Returns the current system date.
INSERT INTO FRIENDS(Name,Gender,Email,DOB)
VALUES('Mubeen','Male','mubeen@gmail.com',DATE '2021-02-14');

INSERT INTO FRIENDS(Name,Gender,Email,DOB)
VALUES('Murtasim','Male','murtasim@gmail.com',DATE '2021-02-14');

--STARTING FROM M
SELECT * FROM FRIENDS WHERE NAME LIKE 'M%';


SELECT * FROM FRIENDS WHERE NAME LIKE '_____';

SELECT * FROM FRIENDS WHERE NAME LIKE '_r%';


SELECT * FROM FRIENDS WHERE NAME LIKE '_____';

SELECT * FROM FRIENDS;

ALTER TABLE FRIENDS
ADD COUNTRY VARCHAR2(10);

UPDATE FRIENDS
SET COUNTRY = 'UAE'
WHERE ID = 1;

UPDATE FRIENDS
SET COUNTRY = 'IND'
WHERE ID = 5;

UPDATE FRIENDS
SET COUNTRY = 'UK'
WHERE ID = 2;

UPDATE FRIENDS
SET COUNTRY = 'PAK'
WHERE ID = 3;

UPDATE FRIENDS
SET COUNTRY = 'IND'
WHERE ID = 4;

UPDATE FRIENDS
SET COUNTRY = 'UAE'
WHERE ID = 6;

UPDATE FRIENDS
SET COUNTRY = 'IND'
WHERE ID = 7;

UPDATE FRIENDS
SET COUNTRY = 'UAE'
WHERE ID = 22;

UPDATE FRIENDS
SET COUNTRY = 'IND'
WHERE ID = 11;


SELECT COUNTRY,COUNT(*) AS PEOPLE_FROM FROM FRIENDS GROUP BY COUNTRY;


--In most GROUP BY queries, the column you SELECT (that is not inside a group function) must also appear in GROUP BY.
SELECT COLUMN_NAME1,
COUNT(*) AS ANYNAME1
FROM Friends
GROUP BY COLUMN_NAME1;

SELECT age,count(*) as Same_Age from friends
group by age;

SELECT dob,count(*) as Same_Birthdays from friends
group by dob;

commit;

SELECT COUNT(*) AS Total_Friends
FROM Friends;

SELECT FLOOR(AVG(Age)) AS Average_Age
FROM Friends;

SELECT MAX(Age) AS Oldest
FROM Friends;

SELECT SUM(Age) AS Total_Age
FROM Friends;


SELECT *
FROM Friends
WHERE Age = (SELECT MAX(Age) FROM Friends);



